package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.42

import (
	"context"

	"github.com/aereal/poc-graphql-pqs-server/domain"
	"github.com/aereal/poc-graphql-pqs-server/graph"
	"github.com/aereal/poc-graphql-pqs-server/graph/loaders"
)

// Character is the resolver for the character field.
func (r *queryResolver) Character(ctx context.Context, name string) (*domain.Character, error) {
	character, err := loaders.GetCharacterByName(ctx, name)
	if err != nil {
		return nil, err
	}
	return character, nil
}

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
